sonar.projectKey=26_MTask
sonar.projectName=26_MTask
sonar.projectVersion=1.0

sonar.sources=server/src,server/scripts,web/src,electron
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/data/**,**/*.d.ts

sonar.typescript.tsconfigPaths=server/tsconfig.json,web/tsconfig.json

sonar.sourceEncoding=UTF-8
